# Vector Intersection
To realize some form of geometrical connection between the pads of two given footprints, whether it is a parametric curve or otherwise, it is often useful to compute the vectors of each pad selected by the user. In doing so, an intersection point can be determined from two vector line equations that in turn provide information about how a copper track extends from a selected pad. Computing the pad-vectors is accomplished by subtracting the center point of the selected pad by the center point of the corresponding footprint.

## Equation Setup
Suppose we have an 0402 footprint with center point $(6.5, 3)$ and the user selects a pad on that same footprint with center point $(6.5, 3.017716535)$. A vector, $\vec{P_0}$, can be computed from the center of the footprint to the center of the pad:

\begin{equation*}
    \vec{P_0} =
    \begin{pmatrix}
        6.5 - 6.5 \\
        3.017716535 - 3
    \end{pmatrix} =
    \begin{pmatrix}
        0 \\
        0.017717
    \end{pmatrix}
\end{equation*}

Let us also assume the user has placed another 0402 footprint with footprint center point $(6.6, 3.2)$ and selected pad center point $(6.582283465, 3.2)$. A similar vector, $\vec{P_1}$, can be computed:

\begin{equation*}
    \vec{P_1} =
    \begin{pmatrix}
        6.582283465 - 6.6 \\
        3.2 - 3.2
    \end{pmatrix} =
    \begin{pmatrix}
        -0.01772 \\
        0
    \end{pmatrix}
\end{equation*}

This yields the following vector line equations, in the form $\vec{B} = \vec{P_i} + \vec{A}t$:

\begin{equation*}
    \vec{v} =
    \begin{pmatrix}
        6.5 \\
        3
    \end{pmatrix} +
    \begin{pmatrix}
        0 \\
        0.017717
    \end{pmatrix}t
\end{equation*}

\begin{equation*}
    \vec{w} =
    \begin{pmatrix}
        6.6 \\
        3.2
    \end{pmatrix} +
    \begin{pmatrix}
        -0.01772 \\
        0
    \end{pmatrix}u
\end{equation*}

# Intersection Point
The intersection point of both lines occurs when the $(x, y)$ coordinates are equal. Let us compute this by hand first in order to understand what is happening:

\begin{equation*}
    6.5 + (0)t = 6.6 + (-0.01772)u \\
    3 + (0.017717)t = 3.2 + (0)u \\ \\
    \Rightarrow t = 5.64429644, \text{ } u = 11.28668172
\end{equation*}

# Python Implementation
Now let us have Python solve for the intersection point. To do this, it is helpful to represent the equations in classic $\mathbf{A}x = \mathbf{B}$ form first, in which we want to solve for $x$:

\begin{equation*}
    a_1 = (0)t - (-0.01772)u \\
    a_2 = (0.017717)t - (0)u \\
    \therefore \vec{A} =
    \begin{pmatrix}
        0 & 0.01772 \\
        0.017717 & 0
    \end{pmatrix} \\
    b_1 = w_x - v_x \\
    b_2 = w_y - v_y \\
    \therefore \vec{B} = 
    \begin{pmatrix}
        6.6 - 6.5 \\
        3.2 - 3
    \end{pmatrix} = 
    \begin{pmatrix}
        0.1 \\
        0.2
    \end{pmatrix}
\end{equation*}

In [1]:
import numpy as np

a = np.array([[0, 0.01772], [0.017717, 0]])
b = np.array([(6.6-6.5), (3.2-3)])

x = np.linalg.solve(a, b)
x

array([11.28859288,  5.64334086])

# Final Intersection Point
While the above Python solution satisfies the solution for $x$, it is not our final intersection point. Next, we must substitute our solution in for either $\vec{v}$ or $\vec{w}$.

In [2]:
t = x[0]
u = x[1]

v = np.array([6.5, 3]) + np.array([0, 0.017717])*t
w = np.array([6.6, 3.2]) + np.array([-0.01772, 0])*u

In [3]:
v

array([6.5, 3.2])

In [4]:
w

array([6.5, 3.2])

Thus, the two vectors $\vec{v}$ and $\vec{w}$ intersect at the point $(6.5, 3.2)$.